name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push container image
      uses: actions/docker/cli@v2
      with:
        args: build -t myimage:${{ env.TAG }} .
        
    - name: Login to Azure 
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to AKS
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: my-cluster
    - name: Apply kubeconfig
      run: |-
        kubectl config set-context --current --namespace=production
        kubectl apply -f k8s/deployment.yaml
